const startButtonSelector = ".button__start"
const stopButtonSelector = ".button__stop"
const hoursInputSelector = "#hours"
const minutesInputSelector = "#minutes"
const secondsInputSelector = "#seconds"